### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by armkillbill** [gr2m/iterate-cron-action#1]
Hi,

Thanky you for your tool, very helpful.

It would be great for this action to have baseUrl input for using in different environment other than "https://api.github.com".

Right now that URL is the default baseUrl of Octokit.

**Comment by gr2m** [comment]
this is for GHES, right? I don't mind adding an option to make that possible. Are you aware of any conventions that other actions use to be compatible with GitHub Enterprise Server?

**Comment by jumanjiman** [comment]
> this is for GHES, right?

yes, this request is to support github enterprise instances.

> I don't mind adding an option to make that possible. 

Thank you!

> Are you aware of any conventions that other actions use to be compatible with GitHub Enterprise Server?

The `GITHUB_API_URL` and `GITHUB_GRAPHQL_URL` environment variables are automatically available to all actions and workflows as described at https://docs.github.com/en/actions/learn-github-actions/environment-variables

Here's a recent PR for an action that is based on octokit js: https://github.com/abaplint/actions-abaplint/pull/23

Here's another example to get the value of the env var: https://github.com/eps1lon/actions-label-merge-conflict/blob/50c9841a4352dbde3ac9cbc523882050cf6531e7/dist/index.js#L566-L568

**Comment by gr2m** [comment]
Thanks Paul. 

I'd happily accept a PR that takes `GITHUB_API_URL` into account

**Comment by jumanjiman** [comment]
Thank you!

i'll put something together unless @armkillbill beats me to it.

**Comment by armkillbill** [comment]
I have created a PR.
