### ISSUE TITLE
How would I use this to run a workflow once every 2 weeks?

### ISSUE THREAD

**Issue by clubanderson** [gr2m/iterate-cron-action#3]
How can I run a workflow, that creates a community meeting issue, once every 2 weeks?

**Comment by gr2m** [comment]
You don't need this action.

You can use the `schedule` setting to trigger the action e.g. on the 1st and 14th of each month, and then use one of the actions to create an issue.

**Comment by clubanderson** [comment]
Nope. Every 2 weeks. Not the 1st and 14th

**Comment by clubanderson** [comment]
Every two weeks on a Thursday

**Comment by gr2m** [comment]
I think that the cron syntax actually does not support that, unfortunately. In that case I'd probably run it daily and then add a check if today is the first or 3rd Thursday of the week.

**Comment by clubanderson** [comment]
It actually has to be done with week numbers. Odd numbered weeks and Thursday.

**Comment by gr2m** [comment]
You'll have to figure out the pieces yourself, this is something I'd do as contractor, but I'm not available.
You might also have better luck asking general GitHub Actions questions in https://github.com/orgs/community/discussions/categories/actions, maybe someone solved the problem you did before.

**Comment by clubanderson** [comment]
I figured it out already. Just checking to see if your work could help.
